# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCostMaintenance < Formula
  desc "Collection of scripts that analyze easily correctable items to save money in AWS."
  homepage "https://www.jmoney8080.dev"
  version "0.1.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jmoney8080/aws-cost-maintenance/releases/download/v0.1.11/aws-cost-maintenance_0.1.11_darwin_amd64.tar.gz"
    sha256 "fec798f965a920866eea16d05621a8e8c0ee95ab6756716609bbdf26831b7b4d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jmoney8080/aws-cost-maintenance/releases/download/v0.1.11/aws-cost-maintenance_0.1.11_linux_amd64.tar.gz"
      sha256 "58f5b81037c1160b354a3968e4d62883063703cfcbd9f22456d9c8f7a0337228"
    end
  end

  def install
    bin.install "aws-cost-maintenance"
  end

  test do
    system "#{bin}/aws-cost-maintenance -h"
  end
end
