# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LambdaInventory < Formula
  desc "Takes inventory of the lambda service in AWS configured by a yaml file."
  homepage "https://jmoney.dev/lambda-inventory"
  version "0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/lambda-inventory/releases/download/v0.1/lambda-inventory_0.1_darwin_arm64.tar.gz"
      sha256 "203dcf7e5371837bf111610241defa94695d4aed64c3c03cf2c3897128673308"

      def install
        bin.install "lambda-inventory"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/lambda-inventory/releases/download/v0.1/lambda-inventory_0.1_darwin_amd64.tar.gz"
      sha256 "80cbd2424683422a20bb0056ac9991515f56ee13ae6d76f39ca69859dc8fdf1f"

      def install
        bin.install "lambda-inventory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/lambda-inventory/releases/download/v0.1/lambda-inventory_0.1_linux_arm64.tar.gz"
      sha256 "47760d389d062f6977deff18fe077a630144a945846bcd67e4c7e23da90b835f"

      def install
        bin.install "lambda-inventory"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/lambda-inventory/releases/download/v0.1/lambda-inventory_0.1_linux_amd64.tar.gz"
      sha256 "9029fb4e9d35f7ffa83a1c12c7415141ba6576c3ce82b7c1130db9dfd774b404"

      def install
        bin.install "lambda-inventory"
      end
    end
  end

  test do
    system "#{bin}/lambda-inventory -h"
  end
end
