# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RebootEcsServiceATv01 < Formula
  desc "Reboots an ECS service"
  homepage "https://jmoney.dev/reboot-ecs-service"
  version "0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/reboot-ecs-service/releases/download/v0.1/reboot-ecs-service_0.1_darwin_arm64.tar.gz"
      sha256 "c9e459521eecbde7ffc1bcf3fa30ede356a91b79ba9ace5c31199e1ca7c4c504"

      def install
        bin.install "reboot-ecs-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/reboot-ecs-service/releases/download/v0.1/reboot-ecs-service_0.1_darwin_amd64.tar.gz"
      sha256 "9375eba8e49fca815b97dcbcef2ed6f2b708756839fcb9f46df849dc43dd8719"

      def install
        bin.install "reboot-ecs-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/reboot-ecs-service/releases/download/v0.1/reboot-ecs-service_0.1_linux_arm64.tar.gz"
      sha256 "d3fa2307c5a3a5ef6840a712da5cbdfe52f3a4867b1a037b9878a5a89891bdb8"

      def install
        bin.install "reboot-ecs-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/reboot-ecs-service/releases/download/v0.1/reboot-ecs-service_0.1_linux_amd64.tar.gz"
      sha256 "d660d97be0fa818d468d7ac4286c3ab7fde3b307bd41ce6ef56c6087079770fa"

      def install
        bin.install "reboot-ecs-service"
      end
    end
  end

  test do
    system "#{bin}/reboot-ecs-service -h"
  end
end
