# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3MultipartUploadATv03 < Formula
  desc "Multipart uploads files to s3 with checkpointing"
  homepage "https://jmoney.dev/s3-multipart-upload"
  version "0.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.3/s3-multipart-upload_0.3_darwin_amd64.tar.gz"
      sha256 "01d667a2512115fb3feb1a990fb8d4c48bd7222c9526f5018a4c7a1e884ee792"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.3/s3-multipart-upload_0.3_darwin_arm64.tar.gz"
      sha256 "45ee947fb04b9a430934a00128c1d482a1ddcf4353935d4ed1fa31346829092b"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.3/s3-multipart-upload_0.3_linux_arm64.tar.gz"
      sha256 "410e988b4c3bc4d9a7259520826cd933d5a426c668262108d47468f08659b32b"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.3/s3-multipart-upload_0.3_linux_amd64.tar.gz"
      sha256 "8e5ef2073b16f569052f007a036835a3f5e732346d9acdb835aa673e5be415f9"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  test do
    system "#{bin}/s3-multipart-upload -h"
  end
end
