# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3MultipartUpload < Formula
  desc "Multipart uploads files to S3 with checkpointing"
  homepage "https://jmoney.dev/s3-multipart-upload"
  version "0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.1/s3-multipart-upload_0.1_darwin_arm64.tar.gz"
      sha256 "3ab1748c91ca95d73d0b5355f288544119c1ec490913ce36b89a141f8bb3bc0e"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.1/s3-multipart-upload_0.1_darwin_amd64.tar.gz"
      sha256 "9d6e4290bcec6777198c29aeb82e5c839fd712b5dc95c1f3c99988215f7363fb"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.1/s3-multipart-upload_0.1_linux_arm64.tar.gz"
      sha256 "d8e523beed6b55abb29a44458d9f22d1842dad7096377c0ce8065aa77ec8ac7b"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.1/s3-multipart-upload_0.1_linux_amd64.tar.gz"
      sha256 "e8826a01ad281f862ec77da7bc535a6a261f8afd2799ef6c8a263f44da16fef3"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  test do
    system "#{bin}/s3-multipart-upload -h"
  end
end
