# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3MultipartUploadATv02 < Formula
  desc "Multipart uploads files to s3 with checkpointing"
  homepage "https://jmoney.dev/s3-multipart-upload"
  version "0.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.2/s3-multipart-upload_0.2_darwin_arm64.tar.gz"
      sha256 "c853352969ce525285e5709a58a9a16bfafe24ef7e8febd6fbe17d54bb92f19f"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.2/s3-multipart-upload_0.2_darwin_amd64.tar.gz"
      sha256 "d22aa986dbcb6b7044dab659c074209652488146c7993cea1c90ed3592cdbc83"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.2/s3-multipart-upload_0.2_linux_arm64.tar.gz"
      sha256 "c7f9eda9960fa06ff8ecac3feab200afa312926d45d482ae79af3607887c3ec4"

      def install
        bin.install "s3-multipart-upload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/s3-multipart-upload/releases/download/v0.2/s3-multipart-upload_0.2_linux_amd64.tar.gz"
      sha256 "6e3b78e9b2583c3b2f3420d7bf49ddde44f3181482b6312013285e56cf2f846d"

      def install
        bin.install "s3-multipart-upload"
      end
    end
  end

  test do
    system "#{bin}/s3-multipart-upload -h"
  end
end
