# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SagemakerEndpointManagementATv05 < Formula
  desc "Management utility for AWS Sagemaker Endpoints"
  homepage "https://jmoney.dev/sagemaker-endpoint-management"
  version "0.5"
  license "Apache 2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/sagemaker-utilities/releases/download/v0.5/sagemaker-endpoint-management_0.5_darwin_arm64.tar.gz"
      sha256 "0a08de3cec3b23cd1b10050f596a01afa0fa6dbcf73421962f28326c8990fb89"

      def install
        bin.install "sagemaker-endpoint-management"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/sagemaker-utilities/releases/download/v0.5/sagemaker-endpoint-management_0.5_darwin_amd64.tar.gz"
      sha256 "2b4c0a587ff443977bd57fa56d6ebecf3bdceaeb738c01b02653de83b6fda61b"

      def install
        bin.install "sagemaker-endpoint-management"
      end
    end
  end

  test do
    system "#{bin}/sagemaker-endpoint-management -h"
  end
end
